import { test } from '@japa/runner'
import BaseSyncModel from '#models/base_sync_model'
import { calendarSourceTypes } from '#models/calendar_source'
import { eventSources } from '#models/event'
import { taskPriorities, taskStatuses } from '#models/task'

test.group('Agenda model contracts', () => {
  test('generates a UUID when the client did not provide one', ({ assert }) => {
    const model = new BaseSyncModel()

    BaseSyncModel.assignUuid(model)

    assert.match(model.id, /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)
  })

  test('preserves a UUID generated by an offline client', ({ assert }) => {
    const model = new BaseSyncModel()
    const clientId = '0199a6d5-e506-7e3e-8f5f-775f3442bd24'
    model.id = clientId

    BaseSyncModel.assignUuid(model)

    assert.equal(model.id, clientId)
  })

  test('exposes the persisted enum values used by API validation', ({ assert }) => {
    assert.deepEqual(taskStatuses, [
      'inbox',
      'todo',
      'scheduled',
      'in_progress',
      'completed',
      'cancelled',
    ])
    assert.deepEqual(taskPriorities, ['none', 'low', 'medium', 'high', 'urgent'])
    assert.deepEqual(eventSources, ['local', 'ics', 'external'])
    assert.deepEqual(calendarSourceTypes, ['local', 'ics_url', 'ics_file'])
  })
})
